---
- hosts: all
  become: yes
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: 'install python'
      raw: sudo apt-get -y install python

- hosts: all
  gather_facts: true
  tags: always

- import_playbook: ubuntu.yml
  tags: ubuntu

- import_playbook: docker.yml
  tags: docker
